### ISSUE TITLE
TODO for re-write

### ISSUE THREAD

**Issue by zhiyan114** [zhiyan114/Firey-Bot#45]
Time to get this garbage cleaned up:
- [x] Disable workflow unless performing PR
- [x] Reorganize the config and have it accessible via the new class
- [x] Create a new class by inheriting Discord Client Class and have all the critical class accessible by it (such as Redis, Postgres, AMQP Connection, config, etc.)
- [x] Commands/services will NO LONGER be loaded via require. Instead, use import all of it manually and load it that way
- [ ] Add a system that automatically `patch` the guild commands list IF hash mismatch (perhaps, SHA512, the bigger the better?)
- [ ] Ensure there's no longer cross-requiring large sum of files files, especially to `index.ts` (I dont even know why I did that years ago..)
- [ ] Reorganize the eval command due to some issue mentioned above (i.e. REMOVE MANUAL slash command register function)
- [ ] Set redis to use docker compose server by default so that it no longer screams "Reconnect" every second (change the dockerfile as well to implement such)...
- [x] Integrate sentry.io metrics to track command usages.
  - Only increment integers are tracked, user who runs the command are not (except certain moderation command)

Stuff found to improve during refactor:
- [x] Remove HTTPS Cert option from `webServer` (Literally only used to receive insensitive webhook callbacks)
- [x] Create a db table to handle auto-gen configs (such as reactionRole message ID)+
- [ ] Modify twitch/youtube notification system to automatically handle everyone/here ping vs role ID
- [x] Have sentry drop event for `P1017` (Prisma) because that suppose to be automatically handled, but somehow exception is thrown???
- [ ] Allow config to be edited without rebuilding the source using docker volume magic...
